// 文档生成服务 Go SDK 使用示例
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/Mars-Sea/doc-gen-service/sdk/go/docgen"
)

func main() {
	// 创建客户端
	client := docgen.NewClient("http://localhost:8081")

	// 示例1: 简单文档生成
	simpleExample(client)

	// 示例2: 带表格循环的文档
	tableExample(client)

	// 示例3: 自定义文件名（支持中文）
	customFileNameExample(client)
}

// simpleExample 简单文档生成示例
func simpleExample(client *docgen.Client) {
	fmt.Println("=== 示例1: 简单文档生成 ===")

	data := map[string]any{
		"title":   "Hello World",
		"date":    "2025-01-01",
		"content": "This is a test document generated by Go SDK.",
	}

	doc, err := client.GenerateWord("test-template.docx", data, "simple_doc")
	if err != nil {
		log.Printf("生成文档失败: %v\n", err)
		return
	}

	err = os.WriteFile("simple_doc.docx", doc, 0644)
	if err != nil {
		log.Printf("保存文件失败: %v\n", err)
		return
	}

	fmt.Println("文档已保存: simple_doc.docx")
}

// tableExample 带表格循环的文档示例
func tableExample(client *docgen.Client) {
	fmt.Println("\n=== 示例2: 表格循环文档 ===")

	data := map[string]any{
		"month": "January 2025",
		"goods": []map[string]any{
			{"name": "Product A", "category": "Electronics", "price": 299.99},
			{"name": "Product B", "category": "Clothing", "price": 49.99},
			{"name": "Product C", "category": "Books", "price": 19.99},
		},
	}

	doc, err := client.GenerateWord("loop-table-template.docx", data, "monthly_report")
	if err != nil {
		log.Printf("生成文档失败: %v\n", err)
		return
	}

	err = os.WriteFile("monthly_report.docx", doc, 0644)
	if err != nil {
		log.Printf("保存文件失败: %v\n", err)
		return
	}

	fmt.Println("文档已保存: monthly_report.docx")
}

// customFileNameExample 自定义中文文件名示例
func customFileNameExample(client *docgen.Client) {
	fmt.Println("\n=== 示例3: 中文文件名 ===")

	data := map[string]any{
		"title": "年度报告",
		"date":  "2025年1月",
	}

	// 使用 SaveWord 方法直接保存
	err := client.SaveWord("test-template.docx", data, "年度报告.docx")
	if err != nil {
		log.Printf("生成文档失败: %v\n", err)
		return
	}

	fmt.Println("文档已保存: 年度报告.docx")
}
